version: "2.4"

services:
  rubyapp:
    build:
      context: rubyapp/
      args:
        WITHOUT_GROUPS: none
    volumes:
      - ./rubyapp:/opt/app
  opsbot:
    build:
      context: opsbot/
      args:
        DEVELOPER_MODE: "true"
    volumes:
      - ./opsbot:/opt/app
