version: "2.4"

services:
  rubyapp:
    build:
      context: rubyapp/
      target: dev
    volumes:
      - ./rubyapp:/opt/app
  opsbot:
    build:
      context: opsbot/
    volumes:
      - ./opsbot:/opt/app
