version: "2.4"

services:
  rubyapp:
    build:
      context: rubyapp/
      args:
        bundler_args: ""
      target: builder
    volumes:
      - ./rubyapp:/opt/app
  opsbot:
    build:
      context: opsbot/
    volumes:
      - ./opsbot:/opt/app
