version: "2.4"

services:
  rubyapp:
    build:
      context: rubyapp/
      target: builder
      args:
        WITHOUT_GROUPS: none
    volumes:
      - ./rubyapp:/opt/app
  opsbot:
    build:
      context: opsbot/
    volumes:
      - ./opsbot:/opt/app
