version: 2.1

jobs:
  rubyapp:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - restore_cache:
          key: sandbox-rubyapp-{{ checksum "rubyapp/Gemfile.lock" }}
      - run:
          name: Test
          command: |
            cd rubyapp/
            bundle check --path vendor/bundle || bundle install --path vendor/bundle

            mkdir -p ~/results
            bundle exec rspec --format progress --format RspecJunitFormatter -o ~/results/rspec.xml
      - save_cache:
          key: sandbox-rubyapp-{{ checksum "rubyapp/Gemfile.lock" }}
          paths:
            - rubyapp/vendor/bundle
      - store_test_results:
          path: ~/results

  opsbot:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - restore_cache:
          key: sandbox-opsbot-{{ checksum "opsbot/requirements.txt" }}
      - run:
          name: nosetests
          command: |
            cd opsbot
            pip install --user -r requirements.txt

            mkdir -p ~/results/nose
            nosetests --with-xunit --xunit-file ~/results/nose.xml
      - save_cache:
          key: sandbox-opsbot-{{ checksum "opsbot/requirements.txt" }}
          paths:
            - ~/.cache/pip
            - ~/.local
      - store_test_results:
          path: ~/results

workflows:
  version: 2
  ci:
    jobs:
      - rubyapp
      - opsbot
