version: 2.1

jobs:
  rubyapp:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - run:
          name: All-in-One
          command: |
            cd rubyapp/
            bundle install
            bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
      - store_test_results:
          path: ~/rspec

  opsbot:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run:
          name: All-in-One
          command: |
            cd opsbot
            pip install --user -r requirements.txt
            nosetests --with-xunit
      - store_test_results:
          path: opsbot/nosetests.xml
workflows:
  version: 2
  ci:
    jobs:
      - rubyapp
      - opsbot
