version: 2.1

jobs:
  rubyapp:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - run:
          name: All-in-One
          command: |
            cd rubyapp/
            bundle install
            bundle exec rspec

workflows:
  version: 2
  ci:
    jobs:
      - rubyapp
