version: 2.1

jobs:
  rubyapp:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - run:
          name: rspec
          command: |
            cd rubyapp/
            bundle install

            mkdir -p ~/results
            bundle exec rspec --format progress --format RspecJunitFormatter -o ~/results/rspec.xml
      - store_test_results:
          path: ~/results

  opsbot:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run:
          name: nosetests
          command: |
            cd opsbot
            pip install --user -r requirements.txt

            mkdir -p ~/results/nose
            nosetests --with-xunit --xunit-file ~/results/nose/results.xml
      - store_test_results:
          path: ~/results
workflows:
  version: 2
  ci:
    jobs:
      - rubyapp
      - opsbot
