version: 2.1

jobs:
  rubyapp:
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - run:
          name: All-in-One
          command: |
            cd rubyapp/
            bundle install

            mkdir -p ~/results/rspec
            bundle exec rspec --format progress --format RspecJunitFormatter -o ~/results/rspec/results.xml
      - store_test_results:
          path: ~/results/rspec/results.xml

  opsbot:
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run:
          name: All-in-One
          command: |
            cd opsbot
            pip install --user -r requirements.txt

            mkdir -p ~/results/nose
            nosetests --with-xunit --xunit-file ~/results/nose/results.xml
      - store_test_results:
          path: ~/results
workflows:
  version: 2
  ci:
    jobs:
      - rubyapp
      - opsbot
